// Reducer: a function that returns a peice of the application state
    // our application state is generated by reducer functions
export default function() {
    return [
        { title: 'JavaScript: The Good Parts', pages: 101 },
        { title: 'Harry Potter', pages: 34 },
        { title: 'The Dark Tower', pages: 56 },
        { title: 'Eloquent Ruby', pages: 1 },
        { title: 'Eloquent Javascript', pages: 189 }
    ];
}